name: CopyWorld
version: ${project.version}
main: laakii.izda.copyworld.CopyWorld
commands:
  /create:
    description: create region
    aliases: [do]
  /changeRegion:
    description: change all block of region by regionName
  /paste:
    description: paste region by name


